name: Auto Publish
on:
  workflow_dispatch:
  schedule: [{ cron: 0 * * * * }]

env:
  NAME: "CoolPlayLinBot"
  EMAIL: "130831920+coolplaylinbot@users.noreply.github.com"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          token: ${{ secrets.COOLPLAYLIN_BOT_TOKEN }}
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.0"
          cache: "pip"
          cache-dependency-path: "**/requirements.txt"
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin" # See 'Supported distributions' for available options
          java-version: "17"
      - name: Setup Node.JS
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: false
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Setup Git Info
        run: |
          git config --global user.name "${{ env.NAME }}"
          git config --global user.email "${{ env.EMAIL }}"
      - name: Install Dependencies
        run: |
          python3 -m pip install -r requirements.txt
          pnpm install
          sudo apt install msitools
      - name: Publish
        run: python3 src/main.py ${{ secrets.TOKEN }}
      - name: Format
        run: npm run format
      - name: Post on Always
        if: always()
        run: |
          if [[ -n $(git status -s) ]]; then
          git add .
          git commit -m "Update metadata"
          git push origin --force
          fi